# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Influencer.create(name: "Paul Graham", twitter_id: "@paulg")
Influencer.create(name: "Sam Altman", twitter_id: "@sama")
Influencer.create(name: "Marc Andreessen", twitter_id: "@pmarca")
Influencer.create(name: "Startup L. Jackson", twitter_id: "@StartupLJackson")
Influencer.create(name: "Richard Branson", twitter_id: "@richardbranson")
Influencer.create(name: "Ryan Hoover", twitter_id: "@rrhoover")
Influencer.create(name: "Dave McClure", twitter_id: "@davemcclure")
Influencer.create(name: "Per Stenius", twitter_id: "@Fimpen")
Influencer.create(name: "TechCrunch", twitter_id: "@TechCrunch")
Influencer.create(name: "Mashable", twitter_id: "@mashable")
Influencer.create(name: "Mashable Tech", twitter_id: "@mashabletech")
Influencer.create(name: "Wired", twitter_id: "@WIRED")
Influencer.create(name: "Venture Beat", twitter_id: "@VentureBeat")
Influencer.create(name: "Product Hunt", twitter_id: "@ProductHunt")
Influencer.create(name: "Medium", twitter_id: "@Medium")
Influencer.create(name: "TED Talks", twitter_id: "@TEDTalks")
Influencer.create(name: "Simon Dawlat", twitter_id: "@Virtualgoodz")
Influencer.create(name: "Oskar Sundberg", twitter_id: "@Gori")
Influencer.create(name: "Sebastien Saunier", twitter_id: "@ssaunier")
Influencer.create(name: "Kevin Rose", twitter_id: "@kevinrose")
Influencer.create(name: "Joel Spolsky", twitter_id: "@spolsky")
Influencer.create(name: "Ben Horowitz", twitter_id: "@bhorowitz")
Influencer.create(name: "Hacker News", twitter_id: "@newsycombinator")
Influencer.create(name: "The Hacker News", twitter_id: "@TheHackersNews")
Influencer.create(name: "Quartz", twitter_id: "@qz")
Influencer.create(name: "TNM", twitter_id: "@TNW")
Influencer.create(name: "Elon Musk", twitter_id: "@elonmusk")
